name: playwright.pwc
on:
  workflow_dispatch:
jobs:
  basicTests:
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the job in parallel
        shard: [1, 2, 3]

    name: "Playwright Tests - pwc"
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/playwright:v1.49.0-jammy

    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # https://github.com/actions/runner-images/issues/6775
      - run: |
          echo "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install chrome

      - name: Playwright Tests
        continue-on-error: false
        env:
          CURRENTS_PROJECT_ID: rcthJO
          CURRENTS_RECORD_KEY: 3PKAFflJX5D83w67
        run: |
          npx pwc --shard=${{ matrix.shard }}/${{ strategy.job-total }}