name: Playwright & Currents.dev

on:
  workflow_dispatch:

jobs:
  sharded-test:
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]

    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

    - name: Cache npm dependencies
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: npm ci

    - name: Cache Playwright Browsers
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'


    # STEP 2: Run Playwright tests and Monitor Resources (FIXED INDENTATION)
    - name: Run Playwright tests and Monitor Resources (N= 4 Workers)
      env:
        CURRENTS_PROJECT_ID: rcthJO
        CURRENTS_RECORD_KEY: 3PKAFflJX5D83w67
      run: |
        npx pwc --workers 4 --shard=${{ matrix.shard }}/4
      shell: bash
    # END OF NEW MONITORING STEPS